# Generated by Django 5.0.2 on 2024-04-16 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "publication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("page_begin", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                (
                    "edition_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_authors",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_year_publication",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "source_editor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "civility",
                    models.CharField(
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                ("function", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("about", models.CharField(blank=True, max_length=255, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("index", models.SmallIntegerField()),
                ("sommaire_title", models.CharField(max_length=1000)),
                (
                    "sommaire_label",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sommaire_presentation", models.TextField()),
                ("sommaire_cover", models.TextField(blank=True, null=True)),
                ("sommaire_pdf", models.TextField()),
                (
                    "sommaire_authors",
                    models.ManyToManyField(
                        related_name="sommaires", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_ang", models.CharField(blank=True, max_length=500, null=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("date_accept", models.DateTimeField(blank=True, null=True)),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("abstract_fr", models.TextField()),
                ("abstract_ang", models.TextField(blank=True, null=True)),
                ("file_submit", models.TextField(blank=True, null=True)),
                ("pdf_file", models.TextField(blank=True, null=True)),
                ("keywords_fr", models.TextField(blank=True, null=True)),
                ("keywords_ang", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Initialisation"),
                            (2, "Parrution"),
                            (3, "Publication"),
                        ],
                        default=1,
                    ),
                ),
                ("page_begin", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                ("doi_link", models.TextField(blank=True, null=True)),
                ("orcid_link", models.CharField(blank=True, max_length=255, null=True)),
                ("counter_download", models.IntegerField(default=0)),
                ("image_cover", models.TextField(blank=True, null=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="articles", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="articles_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "numero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="review.numero",
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="review.reference"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("logo", models.TextField(blank=True, null=True)),
                ("editorial_slint", models.TextField()),
                ("editorial_slint_pdf", models.TextField()),
                ("code", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("issn", models.CharField(blank=True, max_length=50, null=True)),
                ("eissn", models.CharField(blank=True, max_length=50, null=True)),
                ("copyright", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, null=True)),
                ("date_update", models.DateTimeField(auto_now_add=True)),
                ("pdf_file", models.TextField(blank=True, null=True)),
                ("order", models.SmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="review.review",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="type_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="review.typesource",
            ),
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.SmallIntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("year", models.CharField(max_length=4)),
                (
                    "pages_count",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="review.review",
                    ),
                ),
            ],
            options={
                "ordering": ["-index"],
            },
        ),
        migrations.AddField(
            model_name="numero",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="numeros",
                to="review.volume",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecontent",
            constraint=models.UniqueConstraint(
                fields=("review", "title"), name="unique_title_by_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="pagecontent",
            constraint=models.UniqueConstraint(
                fields=("review", "order"), name="unique_order_by_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("review", "index"), name="unique_index_by_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="volume",
            constraint=models.UniqueConstraint(
                fields=("review", "year"), name="unique_year_by_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="numero",
            constraint=models.UniqueConstraint(
                fields=("index", "volume"), name="unique_in_num_review"
            ),
        ),
    ]
