# Generated by Django 5.0.2 on 2024-03-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('logo', models.TextField(blank=True, null=True)),
                ('editorial_slint', models.TextField()),
                ('editorial_slint_pdf', models.TextField()),
                ('code', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=4)),
                ('pages_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='review.review')),
            ],
            options={
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('index', models.SmallIntegerField()),
                ('sommaire_title', models.CharField(max_length=500)),
                ('sommaire_label', models.CharField(blank=True, max_length=200, null=True)),
                ('sommaire_presentation', models.TextField()),
                ('sommaire_cover', models.TextField(blank=True, null=True)),
                ('sommaire_pdf', models.TextField()),
                ('sommaire_authors', models.ManyToManyField(related_name='sommaires', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numeros', to='review.volume')),
            ],
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('review', 'index'), name='unique_index_by_review'),
        ),
        migrations.AddConstraint(
            model_name='volume',
            constraint=models.UniqueConstraint(fields=('review', 'year'), name='unique_year_by_review'),
        ),
        migrations.AddConstraint(
            model_name='numero',
            constraint=models.UniqueConstraint(fields=('index', 'volume'), name='unique_in_num_review'),
        ),
    ]
