# Generated by Django 5.0.2 on 2024-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numero',
            name='sommaire_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numero',
            name='sommaire_presentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numero',
            name='sommaire_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
