# Generated by Django 5.0.1 on 2024-03-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
