# Generated by Django 5.0.2 on 2024-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_article_title_ang_alter_article_title_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
