# Generated by Django 5.0.1 on 2024-03-14 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_author_institution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="numero",
            name="sommaire_title",
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "publication",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("page_begin", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                (
                    "edition_ref",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_authors",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_city", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source_year_publication",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "source_editor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "type_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="review.typesource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_fr", models.CharField(max_length=255)),
                ("title_ang", models.CharField(blank=True, max_length=255, null=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("date_accept", models.DateTimeField(blank=True, null=True)),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("abstract_fr", models.TextField()),
                ("abstract_ang", models.TextField(blank=True, null=True)),
                (
                    "file_submit",
                    models.FileField(
                        blank=True, null=True, upload_to="files-submit/articles"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="files-submit/articles"
                    ),
                ),
                ("keywords_fr", models.TextField(blank=True, null=True)),
                ("keywords_ang", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (1, "Initialisation"),
                            (2, "Parrution"),
                            (3, "Publication"),
                        ],
                        default=1,
                    ),
                ),
                ("page_begin", models.IntegerField(blank=True, null=True)),
                ("page_end", models.IntegerField(blank=True, null=True)),
                ("doi_link", models.TextField(blank=True, null=True)),
                ("orcid_link", models.CharField(blank=True, max_length=255, null=True)),
                ("counter_download", models.IntegerField(default=0)),
                (
                    "image_cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="pictures/articles-cover"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="articles", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "numero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.numero",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="articles_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(blank=True, to="review.reference"),
                ),
            ],
        ),
    ]
