# Generated by Django 5.0.2 on 2024-03-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_numero_sommaire_title_reference_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_submit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='review.numero'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='articles', to='review.reference'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ang',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=500),
        ),
    ]
