# Generated by Django 5.0.2 on 2024-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_author_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(),
        ),
    ]
