# Generated by Django 5.0.2 on 2024-08-23 17:11

from django.db import migrations

def initial_data(apps, schema_editor):
    TypeSource = apps.get_model('review', 'TypeSource')

    TypeSource.objects.create(name="journal")
    TypeSource.objects.create(name="livre")

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_title'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
