# Generated by Django 5.0.2 on 2024-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_article_file_submit_alter_article_image_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='eissn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='issn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
