# Generated by Django 5.0.2 on 2024-03-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_pagecontent_pagecontent_unique_title_by_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name="pagecontent",
            constraint=models.UniqueConstraint(
                fields=("review", "order"), name="unique_order_by_review"
            ),
        ),
    ]
