# Generated by Django 5.0.2 on 2024-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0008_pagecontent_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="copyright",
            field=models.TextField(blank=True, null=True),
        ),
    ]
