# Generated by Django 5.0.2 on 2024-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='civility',
            field=models.SmallIntegerField(),
        ),
    ]
