# Generated by Django 5.0.2 on 2024-03-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('order', models.SmallIntegerField(default=0, null=True, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Branche',
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Liasse',
            },
        ),
        migrations.CreateModel(
            name='CategoryTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('ordering', models.PositiveSmallIntegerField(unique=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='country/flag')),
                ('nationality_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Echelon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Echelle',
            },
        ),
        migrations.CreateModel(
            name='PersonalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Classe personnelle',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Specialité',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_number', models.IntegerField(choices=[(1, 'Classe 1'), (2, 'Classe 2'), (3, 'Classe 3'), (4, 'Classe 4'), (5, 'Classe 5'), (6, 'Classe 6'), (7, 'Classe 7'), (8, 'Classe 8'), (9, 'Classe 9')], verbose_name='Classe')),
                ('code', models.CharField(max_length=10, verbose_name='Numéro compte')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('credit_balance', models.FloatField(default=0, verbose_name='Solde Crédit')),
                ('debit_balance', models.FloatField(default=0, verbose_name='Solde Dédit')),
                ('senc_dc', models.CharField(blank=True, choices=[('Debit', 'DEBIT'), ('credit', 'CREDIT'), ('debit & credit', 'DEBIT & CREDIT')], max_length=20, null=True, verbose_name='SENS_DC')),
                ('is_chapter', models.BooleanField(blank=True, null=True, verbose_name='Est compte chapitre')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_account', to='academic_years.academicyear', verbose_name='Année académique')),
                ('credit_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_account_credit', to='config_global.bundle', verbose_name='Liasse Crédit')),
                ('debit_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_account_debit', to='config_global.bundle', verbose_name='Liasse Dédit')),
            ],
            options={
                'verbose_name': 'Plan comptable',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('max_withdrawal_per_period', models.FloatField(verbose_name='Retrait maximum par période')),
                ('max_withdrawal_per_transaction', models.FloatField(verbose_name='Retrait maximum par opération')),
                ('max_withdrawal_period', models.FloatField(verbose_name='Periode de Retrait maximum')),
                ('payment_authorized', models.BooleanField(default=True, verbose_name='Versement autorisé')),
                ('withdrawal_authorized', models.BooleanField(default=True, verbose_name='Transfert intercaisse autorisé')),
                ('inter_cash_transfer_authorized', models.BooleanField(default=True, verbose_name='Transfert intercaisse autorisé')),
                ('cash_balance', models.BooleanField(default=0, verbose_name='Solde actuel')),
                ('bank_withdrawal_transfer_authorized', models.BooleanField(default=True, verbose_name='Tansfert/retrait banque autorisé')),
                ('is_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_year', to='academic_years.academicyear', verbose_name='Année académique')),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_chart', to='config_global.chartofaccount', verbose_name='Compte associé')),
            ],
            options={
                'verbose_name': 'Caisse',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('ordering', models.PositiveSmallIntegerField(unique=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departement', to='config_global.country', verbose_name='Pays')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('order', models.SmallIntegerField(default=0, null=True, verbose_name='Ordre')),
                ('examen_nivel', models.BooleanField(default=False, verbose_name="Est-un niveau d'examen")),
                ('branchs', models.ManyToManyField(related_name='nivels', to='config_global.branch')),
            ],
            options={
                'verbose_name': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('order', models.SmallIntegerField(default=0, null=True, verbose_name='Ordre')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_class', to='config_global.branch', verbose_name='Branche')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel_class', to='config_global.nivel', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Classe',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branch', to='config_global.speciality', verbose_name='Specialité'),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('ordering', models.PositiveSmallIntegerField(unique=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='town', to='config_global.country')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
    ]
