# Generated by Django 5.0.1 on 2024-01-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=255)),
                (
                    "max_withdrawal_per_period",
                    models.FloatField(verbose_name="Retrait maximum par période"),
                ),
                (
                    "max_withdrawal_per_transaction",
                    models.FloatField(verbose_name="Retrait maximum par opération"),
                ),
                (
                    "max_withdrawal_period",
                    models.FloatField(verbose_name="Periode de Retrait maximum"),
                ),
                (
                    "payment_authorized",
                    models.BooleanField(
                        default=True, verbose_name="Versement autorisé"
                    ),
                ),
                (
                    "withdrawal_authorized",
                    models.BooleanField(
                        default=True, verbose_name="Transfert intercaisse autorisé"
                    ),
                ),
                (
                    "inter_cash_transfer_authorized",
                    models.BooleanField(
                        default=True, verbose_name="Transfert intercaisse autorisé"
                    ),
                ),
                (
                    "cash_balance",
                    models.BooleanField(default=0, verbose_name="Solde actuel"),
                ),
                (
                    "bank_withdrawal_transfer_authorized",
                    models.BooleanField(
                        default=True, verbose_name="Tansfert/retrait banque autorisé"
                    ),
                ),
                ("is_actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Caisse",
            },
        ),
        migrations.CreateModel(
            name="CategoryTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("ordering", models.PositiveSmallIntegerField(unique=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("flag", models.ImageField(upload_to="country/flag")),
                ("nationality_label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Pays",
            },
        ),
        migrations.CreateModel(
            name="Echelon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ladder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Echelle",
            },
        ),
        migrations.CreateModel(
            name="PersonalClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Classe personnelle",
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
            ],
            options={
                "verbose_name": "Specialité",
            },
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("ordering", models.PositiveSmallIntegerField(unique=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departement",
                        to="config_global.country",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                ("ordering", models.PositiveSmallIntegerField(unique=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="town",
                        to="config_global.departement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ville",
            },
        ),
    ]
