# Generated by Django 5.0.2 on 2024-04-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_global", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="capacity_max",
            field=models.IntegerField(default=0, verbose_name="Capacité max"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="current_capacity",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Nombre d'inscrits"
            ),
        ),
    ]
