# Generated by Django 5.0.1 on 2024-01-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_global", "0002_alter_country_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
            ],
            options={
                "verbose_name": "Liasse",
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "credit_balance",
                    models.FloatField(default=0, verbose_name="Solde Crédit"),
                ),
                (
                    "debit_balance",
                    models.FloatField(default=0, verbose_name="Solde Dédit"),
                ),
                (
                    "senc_dc",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Debit", "DEBIT"),
                            ("credit", "CREDIT"),
                            ("debit & credit", "DEBIT & CREDIT"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="SENS_DC",
                    ),
                ),
                ("is_chapter", models.BooleanField(blank=True, null=True)),
                (
                    "clase_number",
                    models.IntegerField(
                        choices=[
                            (1, "Classe 1"),
                            (2, "Classe 2"),
                            (3, "Classe 3"),
                            (4, "Classe 4"),
                            (5, "Classe 5"),
                            (6, "Classe 6"),
                            (7, "Classe 7"),
                            (8, "Classe 8"),
                            (9, "Classe 9"),
                        ]
                    ),
                ),
                (
                    "credit_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_account_credit",
                        to="config_global.bundle",
                        verbose_name="Liasse Crédit",
                    ),
                ),
                (
                    "debit_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_account_debit",
                        to="config_global.bundle",
                        verbose_name="Liasse Dédit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan comptable",
            },
        ),
    ]
