# Generated by Django 5.0.2 on 2024-04-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_global", "0002_classroom_capacity_max_classroom_current_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0, null=True, verbose_name="Ordre"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AlterModelOptions(
            name="nivel",
            options={"ordering": ("order",), "verbose_name": "Niveau"},
        ),
        migrations.RemoveField(
            model_name="nivel",
            name="parcours",
        ),
        migrations.AddField(
            model_name="nivel",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nivel",
                to="config_global.cycle",
            ),
        ),
    ]
