# Generated by Django 3.2.20 on 2024-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_global', '0003_bundle_chartofaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='clase_number',
            field=models.IntegerField(choices=[(1, 'Classe 1'), (2, 'Classe 2'), (3, 'Classe 3'), (4, 'Classe 4'), (5, 'Classe 5'), (6, 'Classe 6'), (7, 'Classe 7'), (8, 'Classe 8'), (9, 'Classe 9')], verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Numéro compte'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='is_chapter',
            field=models.BooleanField(blank=True, null=True, verbose_name='Est compte chapitre'),
        ),
    ]
