# Generated by Django 5.0.2 on 2024-04-17 10:36

from django.db import migrations

# Generated by Django 5.0.2 on 2024-04-17 10:15

from django.db import migrations

def initial_data(apps, schema_editor):
    # Accédez aux modèles
    Cycle = apps.get_model('config_global', 'Cycle')
    data = [
        {'title': 'Licence', 'code': 'LCE'},
        {'title': 'Master', 'code': 'MTR'},
        {'title': 'Doctorat', 'code': 'DRT'},
    ]
    for item in data:
        Cycle.objects.get_or_create(
            code=item['code'],
            label=item['title']
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "config_global",
            "0003_cycle_alter_nivel_options_remove_nivel_parcours_and_more",
        ),
    ]

    operations = []
