# Generated by Django 3.2.20 on 2024-02-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
        ('config_global', '0004_auto_20240204_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='academic_year',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academic_years.academicyear'),
        ),
    ]
