# Generated by Django 3.2.20 on 2024-02-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_global', '0005_box_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='departement',
        ),
        migrations.AddField(
            model_name='town',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='town', to='config_global.country'),
            preserve_default=False,
        ),
    ]
