# Generated by Django 5.0.2 on 2024-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_global", "0005_alter_nivel_cycle_nivel_unique_order_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nivel",
            name="code",
            field=models.CharField(max_length=10, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="nivel",
            name="label",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
    ]
