# Generated by Django 3.2.20 on 2024-02-17 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0004_alter_academicyear_options'),
        ('config_global', '0006_auto_20240213_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='chart_of_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='box',
            name='academic_year',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='academic_years.academicyear'),
            preserve_default=False,
        ),
    ]
