# Generated by Django 5.0.2 on 2024-04-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_global", "0006_alter_nivel_code_alter_nivel_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Pays", "verbose_name_plural": "Pays"},
        ),
        migrations.AlterModelOptions(
            name="generalbacseries",
            options={"verbose_name": "Serie"},
        ),
        migrations.AlterModelOptions(
            name="nivel",
            options={
                "ordering": ("order",),
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
            },
        ),
        migrations.AlterModelOptions(
            name="parcours",
            options={"verbose_name_plural": "Parcours"},
        ),
    ]
