# Generated by Django 3.2.20 on 2024-02-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0004_alter_academicyear_options'),
        ('config_global', '0008_alter_box_chart_of_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='academic_year',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='academic_years.academicyear', verbose_name='Année académique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='academic_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='academic_years.academicyear', verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='box',
            name='chart_of_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='config_global.chartofaccount', verbose_name='Compte associé'),
        ),
    ]
