# Generated by Django 5.0.1 on 2024-02-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_years", "0004_alter_academicyear_options"),
        ("config_global", "0009_auto_20240217_0130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="academic_years.academicyear",
                verbose_name="Année académique",
            ),
        ),
        migrations.AlterField(
            model_name="box",
            name="chart_of_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="config_global.chartofaccount",
                verbose_name="Compte associé",
            ),
        ),
        migrations.AlterField(
            model_name="chartofaccount",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="academic_years.academicyear",
                verbose_name="Année académique",
            ),
        ),
    ]
