# Generated by Django 3.2.20 on 2024-02-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0004_alter_academicyear_options'),
        ('config_global', '0010_alter_box_academic_year_alter_box_chart_of_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_year', to='academic_years.academicyear', verbose_name='Année académique'),
        ),
        migrations.AlterField(
            model_name='box',
            name='chart_of_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='box_chart', to='config_global.chartofaccount', verbose_name='Compte associé'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_account', to='academic_years.academicyear', verbose_name='Année académique'),
        ),
    ]
