# Generated by Django 3.2.20 on 2024-02-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0004_alter_academicyear_options'),
        ('agent', '0010_alter_agent_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField()),
                ('date_save', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('last_update_date', models.DateTimeField(auto_now=True, verbose_name='Dernière modification date')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_added_by', to='agent.agent', verbose_name='Ajouté par')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agent.agent')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_last_update_by', to='agent.agent', verbose_name='Dernière modification par')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_documents', to='academic_years.academicyear', verbose_name='Année académique')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
    ]
