# Generated by Django 5.0.2 on 2024-03-13 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('year_name', models.CharField(max_length=10, unique=True)),
                ('year_begin', models.SmallIntegerField(default=0)),
                ('year_end', models.SmallIntegerField(default=0)),
                ('users', models.ManyToManyField(related_name='years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'ordering': ['-year_end'],
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('year_begin', 'year_end'), name='unique_year_academic'),
        ),
    ]
