# Generated by Django 3.2.20 on 2024-02-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Année Académique'},
        ),
    ]
