# Generated by Django 5.0.2 on 2024-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_years", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="is_completed",
            field=models.BooleanField(default=True),
        ),
    ]
