# Generated by Django 3.2.20 on 2024-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0002_alter_academicyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='year_begin',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='year_end',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('year_begin', 'year_end'), name='unique_year_academic'),
        ),
    ]
