# Generated by Django 3.2.20 on 2024-02-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0003_auto_20240216_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-year_end'], 'verbose_name': 'Année Académique'},
        ),
    ]
