# Generated by Django 5.0.2 on 2024-03-13 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_global', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityArea', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Dernières mise à jour')),
                ('civility', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10, verbose_name='Sexe')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('contact', models.CharField(max_length=30)),
                ('qrcode_img', models.TextField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_birth_city', to='config_global.town', verbose_name='Ville de naissance')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.categoryteacher', verbose_name='Categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_creating', to='teacher.teacher', verbose_name='Ajouté par')),
                ('echelon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.echelon', verbose_name='Echelon')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.grade', verbose_name='Grade')),
                ('ladder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.ladder', verbose_name='Echelle')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_modifier', to='teacher.teacher', verbose_name='Dernière modif par')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_global.country', verbose_name='Nationalité')),
                ('personal_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.personalclass', verbose_name='Classe Personelle')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='config_global.speciality', verbose_name='Specialité')),
                ('town_residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config_global.town', verbose_name='Ville de résidence')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
