# Generated by Django 5.0.1 on 2024-01-27 08:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("config_global", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agents/identity"
                    ),
                ),
                (
                    "matricule",
                    models.CharField(
                        editable=False,
                        max_length=4,
                        unique=True,
                        verbose_name="Matricule",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernières mise à jour"
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Date de naissance")),
                ("contact", models.CharField(max_length=30)),
                ("qrcode_img", models.TextField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "birth_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_birth_city",
                        to="config_global.town",
                        verbose_name="Ville de naissance",
                    ),
                ),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.box",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.categoryteacher",
                        verbose_name="Categorie",
                    ),
                ),
                (
                    "echelon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.echelon",
                        verbose_name="Echelon",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.grade",
                        verbose_name="Grade",
                    ),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.ladder",
                        verbose_name="Echelle",
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.country",
                        verbose_name="Nationalité",
                    ),
                ),
                (
                    "personal_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.personalclass",
                        verbose_name="Classe Personelle",
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.speciality",
                        verbose_name="Specialité",
                    ),
                ),
                (
                    "town_residence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.town",
                        verbose_name="Ville de naissance",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
