# Generated by Django 3.2.20 on 2024-03-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
    ]
