# Generated by Django 5.0.2 on 2024-04-05 07:03
from agent.data import congo_cities, african_countries, roles
from django.db import migrations

def initial_data(apps, schema_editor):
    # Accédez aux modèles
    Agent = apps.get_model('agent', 'Agent')
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    Country = apps.get_model('config_global', 'Country')
    City = apps.get_model('config_global', 'Town')

    for item_country in african_countries:
        country, is_created = Country.objects.get_or_create(
            code=item_country['code'],
            label=item_country['label'],
            ordering=item_country['ordering'],
            nationality_label=item_country['nationality_label']
        )
        if item_country['code'] == "CG" and is_created:
            for city in congo_cities:
                City.objects.create(
                    code=city['code'],
                    label=city['label'],
                    ordering=city['ordering'],
                    country=country
                )

    user = User.objects.create_superuser(username="BONHEUR", email="bonheurmafoundou@gmail.com", password="1234")
    Agent.objects.create(
        birth_city=City.objects.get(code="PN"),
        cityArea="Moungali",
        adress="102 rue de test",
        nationality=Country.objects.get(code="CG"),
        town_residence=City.objects.get(code="BZ"),
        contact="068314433",
        user=User.objects.get(username="bonheur")
    )
    # Créer des groupes si non existants
    for group_name in roles:
        group, is_created = Group.objects.get_or_create(name=group_name)
        if is_created:
            user.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
        ("config_global", "0001_initial"),
    ]
    
    operations = [
         migrations.RunPython(initial_data)
    ]
