# Generated by Django 5.0.1 on 2024-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Detained_dependent_child',
            field=models.FloatField(default=0, verbose_name='Retenue Enfant Charge'),
        ),
        migrations.AddField(
            model_name='agent',
            name='basic_salary',
            field=models.FloatField(default=0, verbose_name='Rémunération de base'),
        ),
        migrations.AddField(
            model_name='agent',
            name='monthly_indaminitis',
            field=models.FloatField(default=0, verbose_name='Indaminité mensuel'),
        ),
        migrations.AddField(
            model_name='agent',
            name='retained_cnss',
            field=models.FloatField(default=0, verbose_name='Retenue CNSS'),
        ),
        migrations.AddField(
            model_name='agent',
            name='retained_insurance',
            field=models.FloatField(default=0, verbose_name='Retenue Assurance'),
        ),
        migrations.AddField(
            model_name='agent',
            name='retained_other',
            field=models.FloatField(default=0, verbose_name='Autre retenue'),
        ),
        migrations.AddField(
            model_name='agent',
            name='retained_social_case',
            field=models.FloatField(default=0, verbose_name='Retenue Cas Social'),
        ),
    ]
