# Generated by Django 3.2.20 on 2024-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
        ('agent', '0003_auto_20240204_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='academic_years',
            field=models.ManyToManyField(related_name='agents', to='academic_years.AcademicYear'),
        ),
    ]
