# Generated by Django 3.2.20 on 2024-03-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0003_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
