# Generated by Django 3.2.20 on 2024-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20240313_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
