# Generated by Django 3.2.20 on 2024-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agent_academic_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
