# Generated by Django 3.2.20 on 2024-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agent_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cityArea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
