# Generated by Django 5.0.1 on 2024-03-13 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_alter_agent_birth_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agent_creating",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ajouté par",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dernière modif par",
            ),
        ),
    ]
