# Generated by Django 3.2.20 on 2024-02-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_agent_cityarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_creating', to='agent.agent', verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_editing', to='agent.agent', verbose_name='Dernière modif par'),
        ),
    ]
