# Generated by Django 5.0.1 on 2024-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0007_alter_agent_created_by_alter_agent_last_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
