# Generated by Django 3.2.20 on 2024-02-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_auto_20240214_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_modifier', to='agent.agent', verbose_name='Dernière modif par'),
        ),
    ]
