# Generated by Django 5.0.1 on 2024-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0008_agent_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="institution",
            field=models.CharField(
                blank=True, default="Marien Ngouabi", max_length=255, null=True
            ),
        ),
    ]
