# Generated by Django 3.2.20 on 2024-02-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_global', '0010_alter_box_academic_year_alter_box_chart_of_account_and_more'),
        ('agent', '0009_alter_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_caisse', to='config_global.box', verbose_name='Caisse'),
        ),
    ]
