# Generated by Django 5.0.2 on 2024-04-05 07:03

from django.db import migrations

def initial_data(apps, schema_editor):
    # Accédez aux modèles
    Agent = apps.get_model('agent', 'Agent')
    Group = apps.get_model('auth', 'Group')

    # Créer des groupes si non existants
    for group_name in ["auteur", "gestionnaire", "doyen", "vice-doyen"]:
        Group.objects.get_or_create(name=group_name)

    # Initialiser des données pour Agent
    """agent_data = {
        'first_name': 'bonheur',
        'last_name': 'mafoundou',
        'email': 'bonheurmafoundou@gmail.com',
        'username': 'bonheur',
        'passowrd': 'azerty'
    }
    Agent.objects.get_or_create(email=agent_data['email'], defaults=agent_data)"""

class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0010_alter_agent_institution"),
    ]

    operations = [
         migrations.RunPython(initial_data)
    ]
