# Generated by Django 5.0.2 on 2024-04-16 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic_years", "0001_initial"),
        ("config_global", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sex",
                    models.SmallIntegerField(choices=[(1, "Fille"), (2, "Garçon")]),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("contact1", models.CharField(max_length=100)),
                ("contact2", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "baccalaureat_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="config_global.generalbacseries",
                    ),
                ),
                (
                    "birth_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_birth_city",
                        to="config_global.town",
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "origin_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_origin_city",
                        to="config_global.town",
                        verbose_name="Ville d'origine",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Préinscription initiale"),
                            (2, "Préinscription validée"),
                            (3, "Inscription validée"),
                            (4, "Inactif"),
                            (5, "Radiation"),
                        ]
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academic_years.academicyear",
                        verbose_name="inscriptions",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.classroom",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="config_global.nivel",
                    ),
                ),
                (
                    "parcours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="config_global.parcours",
                        verbose_name="inscriptions",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions",
                        to="student.student",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inscription",
            constraint=models.UniqueConstraint(
                fields=("student", "academic_year"),
                name="unique_student_by_year_in_insc",
            ),
        ),
    ]
