# Generated by Django 5.0.2 on 2024-04-16 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_years", "0001_initial"),
        ("config_global", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="academic_years.academicyear",
                verbose_name="Année académique",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="class_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config_global.classroom",
                verbose_name="Classe",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="nivel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions",
                to="config_global.nivel",
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="parcours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="config_global.parcours",
                verbose_name="Parcours",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions",
                to="student.student",
                verbose_name="Etudiant",
            ),
        ),
    ]
