# Generated by Django 5.0.2 on 2024-04-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_years", "0001_initial"),
        ("student", "0002_alter_inscription_academic_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_disabled",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_inscription_valid",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_preinscription_valid",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="date_radiation",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="inscription",
            name="disabled_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions_deactivate",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Désactivée par",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="inscription_valid_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions_valid",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Inscription validée par",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="preinscription_valid_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preinscriptions_valid",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Presinscription validée par",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="radiation_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions_radiation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Radiée par",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscriptions",
                to="academic_years.academicyear",
                verbose_name="Année académique",
            ),
        ),
    ]
