# Generated by Django 5.0.2 on 2024-04-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "config_global",
            "0007_alter_country_options_alter_generalbacseries_options_and_more",
        ),
        ("student", "0003_inscription_created_inscription_date_disabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="parcours_suggest",
            field=models.ManyToManyField(
                related_name="student_favourites",
                to="config_global.parcours",
                verbose_name="Parcours souhaités par l'étudiant",
            ),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="parcours",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config_global.parcours",
                verbose_name="Parcours",
            ),
        ),
    ]
