# Generated by Django 5.0.2 on 2024-04-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_inscription_code_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
    ]
